---
name: SAST validation

on:
  pull_request:
  schedule:
    - cron: 0 23 * * 0
permissions:
  pull-requests: write
jobs:
  sast:
    name: Run Bandit Scan (Python only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bandit scan
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
          confidence: high
          exit_zero: true
