---
name: SAST validation

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * 0

jobs:
  sast:
    name: Validate code
    runs-on: ubuntu-latest

    uses: kuchtek/course-actions/.github/workflows/sast-validation-semgrep.yaml@master
    with:
      rules: "p/python"
      upload-artifact: true
      upload-release-assets: false
      upload-results-github-security: false
